name = "Penrose"
uuid = "eeced704-06e5-4138-8d6f-9c072e7a3413"
authors = ["Mike Garrity <mike@rustytriangles.com> and contributors"]
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
