name = "Penrose"
uuid = "eeced704-06e5-4138-8d6f-9c072e7a3413"
authors = ["Mike Garrity <mike@rustytriangles.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
